---
gateway : "192.168.1.1"
dns: "192.168.1.148"

vms_to_create:
 - name: "SiteA"
   ip_address:  "192.168.1.100/24"
   memory: "1024"
   
 - name: "SiteB"
   ip_address: "192.168.1.101/24"
   memory: "1024"
   
 - name: "SiteC"
   ip_address:  "192.168.1.102/24"
   memory: "1024"
 