---
- name: install packages
  apt:
    name: python3-mysqldb
    state: present

- name: copy site_a dump DB
  copy:
    src: sitea.sql
    dest: /tmp

- name: Create the database if not exists
  mysql_db:
     login_user: root
     name: wp
     encoding: utf8mb4
     collation: utf8mb4_unicode_ci
     state: present

- name: Import data into the created database
  shell: |
     mysql -u root wp < /tmp/sitea.sql

- name: create site_a DB user
  mysql_user:
    name: wp
    password: wp
    priv: 'wp.*:ALL'
    state: present